"""
Schemas Pydantic para la API HelpNet
"""
from app.schemas.common import PaginatedResponse, DeleteResponse, CascadeInfo
from app.schemas.organizacion import (
    OrganizacionBase,
    OrganizacionCreate,
    OrganizacionUpdate,
    OrganizacionResponse,
    EmailOrganizacionCreate,
    EmailOrganizacionResponse
)
from app.schemas.proyecto import (
    ProyectoBase,
    ProyectoCreate,
    ProyectoUpdate,
    ProyectoResponse,
    ActividadBase,
    ActividadCreate,
    ActividadUpdate,
    ActividadResponse,
    LocalizacionBase,
    LocalizacionCreate,
    LocalizacionUpdate,
    LocalizacionResponse
)
from app.schemas.voluntario import (
    VoluntarioBase,
    VoluntarioCreate,
    VoluntarioUpdate,
    VoluntarioResponse,
    VoluntarioConEdad,
    SkillBase,
    SkillCreate,
    SkillResponse
)
from app.schemas.recurso import (
    RecursoBase,
    RecursoDonandoCreate,
    RecursoDonandoResponse,
    RecursoAlquiladoCreate,
    RecursoAlquiladoResponse,
    RecursoResponse,
    serialize_recurso
)
from app.schemas.relaciones import (
    ParticipaBase,
    ParticipaCreate,
    ParticipaUpdate,
    ParticipaResponse,
    CoordinaBase,
    CoordinaCreate,
    CoordinaUpdate,
    CoordinaResponse,
    CesionBase,
    CesionCreate,
    CesionUpdate,
    CesionResponse,
    RecursoUsadoCreate,
    RecursoUsadoResponse
)

__all__ = [
    "PaginatedResponse",
    "DeleteResponse",
    "CascadeInfo",
    "OrganizacionBase",
    "OrganizacionCreate",
    "OrganizacionUpdate",
    "OrganizacionResponse",
    "EmailOrganizacionCreate",
    "EmailOrganizacionResponse",
    "ProyectoBase",
    "ProyectoCreate",
    "ProyectoUpdate",
    "ProyectoResponse",
    "ActividadBase",
    "ActividadCreate",
    "ActividadUpdate",
    "ActividadResponse",
    "LocalizacionBase",
    "LocalizacionCreate",
    "LocalizacionUpdate",
    "LocalizacionResponse",
    "VoluntarioBase",
    "VoluntarioCreate",
    "VoluntarioUpdate",
    "VoluntarioResponse",
    "VoluntarioConEdad",
    "SkillBase",
    "SkillCreate",
    "SkillResponse",
    "RecursoBase",
    "RecursoDonandoCreate",
    "RecursoDonandoResponse",
    "RecursoAlquiladoCreate",
    "RecursoAlquiladoResponse",
    "RecursoResponse",
    "serialize_recurso",
    "ParticipaBase",
    "ParticipaCreate",
    "ParticipaUpdate",
    "ParticipaResponse",
    "CoordinaBase",
    "CoordinaCreate",
    "CoordinaUpdate",
    "CoordinaResponse",
    "CesionBase",
    "CesionCreate",
    "CesionUpdate",
    "CesionResponse",
    "RecursoUsadoCreate",
    "RecursoUsadoResponse",
]
